name: Generates Movies List

on:
  schedule:    
    - cron: "0 0 * * 0"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1

    - name: generating
      run: python genmovieslist.py

    - name: push
      run: |
        git config --local user.name "actions"
        git config --local user.email "action@github.com"
        git add *
        git commit -m "sync"
        git push
